name = "cloudflare-proxy"
workers_dev = true
main = "src/index.js"
compatibility_date = "2021-12-07"

[dev]
ip = "0.0.0.0"
port = 8787
local_protocol="http"
upstream_protocol="https"

[vars]
MODE="production"
LOCAL_ADDRESS=""
TARGET_UPSTREAM=""

[env.dev.vars]
MODE="debug"
LOCAL_ADDRESS="http://127.0.0.1:8787"
TARGET_UPSTREAM="https://registry-1.docker.io"

[env.production]
name = "cloudflare-proxy"
routes = [
  { pattern = "docker.wzxmt.xyz", custom_domain = true },
  { pattern = "quay.wzxmt.xyz", custom_domain = true },
  { pattern = "gcr.wzxmt.xyz", custom_domain = true },
  { pattern = "k8s-gcr.wzxmt.xyz", custom_domain = true },
  { pattern = "k8s.wzxmt.xyz", custom_domain = true },
  { pattern = "ghcr.wzxmt.xyz", custom_domain = true },
  { pattern = "cloudsmith.wzxmt.xyz", custom_domain = true },
]

[env.production.vars]
MODE = "production"
TARGET_UPSTREAM = ""
